version: "3.9"

services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_SITE_URL: http://localhost:3000
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_BRAND_NAME: SUNU YARAMA
    ports:
      - "3000:3000"
    env_file:
      - .env.local
